# Generated by Django 2.2 on 2019-04-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res_cus', '0003_auto_20190406_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/food/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res_cus.Food')),
            ],
        ),
    ]
